---
- name: Install MySQL on Ubuntu
  hosts: 10.10.5.82
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: false

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started

    - name: Enable MySQL service on boot
      service:
        name: mysql
        enabled: yes
