---
- name: Install Prometheus Node Exporter on Ubuntu
  hosts: 10.10.5.82  # Replace with the name of your inventory group
  become: false  # Use sudo for privilege escalation

  tasks:
    - name: Download and install Node Exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.darwin-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz
        validate_certs: no

    - name: Extract Node Exporter
      ansible.builtin.unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Create a symlink for Node Exporter
      file:
        src: "/opt/node_exporter-1.6.1.linux-amd64/node_exporter"
        dest: "/usr/local/bin/node_exporter"
        state: link

    - name: Create systemd service for Node Exporter
      systemd:
        name: node_exporter
        enabled: yes
        state: started
        daemon_reload: yes
      notify: restart node_exporter

  handlers:
    - name: restart node_exporter
      service:
        name: node_exporter
        state: restarted
